import { Inter, Exo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const exo = Exo({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${exo.className}`}>
        <Navbar/>
        {children}
        <hr/>
        <Footer/>
      </body>
    </html>
  );
}
